#!/usr/bin/env php
<?php

namespace Core\Cosmos;

require realpath('vendor/autoload.php');

use Core\Abstractions\Enums\FrameworkPath;
use Core\Helpers\FileDirManager;
use Dotenv\Dotenv;
use Exception;
use Symfony\Component\Console\Application;

$env = Dotenv::createImmutable('./');
$env->load();

require FrameworkPath::CORE->additionalPath('Core/global_functions.php');

$cosmo = new Application();

$files = FileDirManager::retrieveFilesByDirectory(
    __DIR__ . '/vendor/vortex-framework/vortex-framework/Core/Cosmo/Commands'
);

$custom_commands = FileDirManager::retrieveFilesByDirectory(
    __DIR__ . '/App/Commands'
);

if ($files !== [] && is_array($files)) {
    foreach ($files as $filename) {
        $command = substr($filename, 0, -4);
        $command =  'Core\Cosmo\Commands\\' . $command;
        $cosmo->add(new $command);
    }
}

if ($custom_commands !== [] && is_array($custom_commands)) {
    foreach ($custom_commands as $custom_command) {
        $command = substr($custom_command, 0, -4);
        $command =  'App\Commands\\' . $command;
        $cosmo->add(new $command);
    }
}

try {
    $cosmo->run();
} catch (Exception $e) {
    echo $cosmo->areExceptionsCaught();
    echo $e->getMessage();
}
