#!/bin/bash

source .env

case $1 in
up)
    docker compose up -d
    ;;
stop)
    docker compose stop
    ;;
down)
    docker compose down
    ;;
exec)
    echo -e "---------------------------------------------------------------------------------
                    ____
                   / ___| _ __   __ _  ___ ___ _ __ ___   __ _ _ __
                   \___ \| '_ \ / _\` |/ __/ _ \ '_ \` _ \ / _\` | '_ \\
                    ___) | |_) | (_| | (_|  __/ | | | | | (_| | | | |
                   |____/| .__/ \__,_|\___\___|_| |_| |_|\__,_|_| |_|
                         |_|
    "
    echo "---------------------------------------------------------------------------------"
    echo Welcome to Vortex docker environment Spaceman!
    echo "---------------------------------------------------------------------------------"
    docker exec -ti --user spaceman $DOCKER_CONTAINER_PREFIX-php-apache bash
    ;;
help)
    echo "> Available commands:"
    echo "- exec  (Execute main Vortex container)"
    echo "- up    (Up application containers)"
    echo "- stop  (Stop application containers)"
    echo "- down  (Remove application containers)"
    ;;
*)
    echo "> Available commands:"
    echo "- exec  (Execute main Vortex container)"
    echo "- up    (Up application containers)"
    echo "- stop  (Stop application containers)"
    echo "- down  (Remove application containers)"
    ;;
esac
